name: GoogleTest

on:
  push:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev

      - name: Configure
        run: cmake -S . -B build

      - name: Build GoogleTest only
        run: cmake --build build --target my_test

      - name: Run GoogleTest
        run: ./build/my_test